name: North County RSS → Slack

on:
  schedule:
    - cron: '0 * * * *'    # top of every UTC hour
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_NORTH: ${{ secrets.SLACK_WEBHOOK_NORTH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore seen-list cache
        uses: actions/cache@v3
        with:
          path: .cache_north
          key: rss-seen-north-${{ github.run_number }}
          restore-keys: |
            rss-seen-north-

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run North County notifier
        run: python rss_notify_north.py

      - name: Save seen-list cache
        uses: actions/cache@v3
        with:
          path: .cache_north
          key: rss-seen-north-${{ github.run_number }}

